# Generated by Django 4.2.30 on 2026-04-27 19:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(help_text='Withdrawal amount in paise (integer, never float)')),
                ('bank_account_id', models.CharField(help_text='Destination bank account identifier', max_length=255)),
                ('idempotency_key', models.UUIDField(help_text='Client-supplied UUID for idempotent requests, scoped per merchant')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of processing attempts (for retry tracking)')),
                ('processing_started_at', models.DateTimeField(blank=True, help_text='When the payout moved to PROCESSING. Used for stuck-payout detection.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(help_text='The merchant requesting the withdrawal', on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='core.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(help_text='Amount in paise. Always positive — direction is indicated by type.')),
                ('type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], help_text='CREDIT increases balance, DEBIT decreases balance', max_length=6)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.merchant')),
                ('payout', models.ForeignKey(blank=True, help_text='The payout this transaction belongs to (null for customer payments)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.payout')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'type'], name='idx_txn_merchant_type'), models.Index(fields=['merchant', '-created_at'], name='idx_txn_merchant_created')],
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['CREDIT', 'DEBIT'])), name='transaction_type_valid'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'updated_at'], name='idx_payout_status_updated'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['merchant', '-created_at'], name='idx_payout_merchant_created'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.UniqueConstraint(fields=('merchant', 'idempotency_key'), name='unique_merchant_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='payout_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'])), name='payout_status_valid'),
        ),
    ]
